import{A as C,i as u,S as E}from"./assets/vendor-ab173345.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const S="42817939-fb8caefadf90676475c3fc719",v="https://pixabay.com/api/";async function p(r,t){const n={key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15},s=`${v}`;return(await C.get(s,{params:n})).data}function h(r){return r.map(t=>{const{webformatURL:n,tags:s,largeImageURL:e,likes:o,views:i,comments:w,downloads:B}=t;return` <li class="gallery-item"> 
                <a class="gallery-link" href="${e}">
                <img  
                  class="gallery-image"
                  src="${n}"
                  alt="${s}"
                />
              </a>
                <ul class="property-list">
      <li class="list-property-item"><strong>Likes</strong> <br> ${o}</li>
      <li class="list-property-item"><strong>Views</strong> <br> ${i}</li>
      <li class="list-property-item"><strong>Comments</strong> <br> ${w}</li>
      <li class="list-property-item"><strong>Downloads</strong> <br> ${B}</li>
    </ul>
            </li>`}).join("")}function P(){return u.error({title:"",backgroundColor:"#c55f5f",titleColor:"#fff",messageColor:"#fff",message:"Please write your request",color:"#fff",position:"topRight",progressBarColor:"#B51B1B"})}function q(){return u.error({title:"",backgroundColor:"#EF4040",titleColor:"#fff",messageColor:"#fff",message:"Sorry, there are no images matching <br/> your search query. Please, try again!",color:"#fff",position:"topRight",progressBarColor:"#B51B1B"})}function M(){return u.warning({message:"We're sorry, but you've reached the end of search results",backgroundColor:"rgb(255, 160, 0)",color:"#fff",position:"topRight"})}function R(r){return u.success({message:`We found ${r} photos`,backgroundColor:"rgb(89, 161, 13)",color:"#fff",position:"topRight"})}const c=document.querySelector(".js-gallery "),$=document.querySelector(".js-search-form"),y=document.querySelector(".loader"),g=document.querySelector(".js-load-more");let l,a,m,f=15;$.addEventListener("submit",T);g.addEventListener("click",O);async function T(r){if(r.preventDefault(),a=1,l=r.currentTarget.elements["user-search-query"].value.trim(),c.innerHTML="",!l){P(),d();return}try{const t=await p(l,a);if(t.hits.length===0)return q();c.innerHTML=h(t.hits),R(t.total),b(),t.total<f?L():j()}catch{}finally{d()}r.target.reset()}const k=new E(".gallery a",{captionsData:"alt",captionDelay:250});function b(){k.refresh()}async function O(){a+=1,A();try{const r=await p(l,a,f);m=Math.ceil(r.total/f);const t=h(r.hits);c.insertAdjacentHTML("beforeend",t),b(),m===a&&(L(),M())}catch{showError("Error")}finally{d()}x()}function x(){const t=c.querySelector(".gallery-item").getBoundingClientRect().height;scrollBy({behavior:"smooth",top:t})}function A(){return y.classList.remove("is-hidden")}function d(){return y.classList.add("is-hidden")}function j(){g.classList.remove("is-hidden")}function L(){g.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
